[package]
name = "aoc-2018"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
crossbeam = "0.8.2"
crossbeam-utils = "0.8.16"
rayon = "1.8.0"
